[versions]
androidVersion = "8.1.2"
kotlinVersion = "1.9.10"

minSdk = "26"
targetSdk = "34"
compileSdk = "34"

coreKtxVersion = "1.12.0"
appcompatVersion = "1.6.1"
materialVersion = "1.11.0"
constraintlayoutVersion = "2.1.4"
splashScreenVersion = "1.0.1"
junitVersion = "4.13.2"
testJunitVersion = "1.1.5"
testEspressoVersion = "3.5.1"
fragmentKtxVersion = "1.6.2"
recyclerviewVersion = "1.3.2"
recyclerviewAnimatorsVersion = "4.0.2"
coroutinesVersion = "1.7.1"
lifecycleVersion = "2.6.2"
viewbindingVersion = "8.2.0"
retrofitVersion = "2.9.0"
okhttpVersion = "4.10.0"
roomVersion = "2.6.1"
glideVersion = "4.14.2"
daggerVersion = "2.45"
navVersion = "2.7.6"
swipreRefreshVersion = "1.1.0"

[libraries]
androidx-core-ktx = { module = "androidx.core:core-ktx", version.ref = "coreKtxVersion" }
fragment-ktx = { module = "androidx.fragment:fragment-ktx", version.ref = "fragmentKtxVersion" }
androidx-appcompat = { module = "androidx.appcompat:appcompat", version.ref = "appcompatVersion" }
android-material = { module = "com.google.android.material:material", version.ref = "materialVersion" }
androidx-constraintlayout = { module = "androidx.constraintlayout:constraintlayout", version.ref = "constraintlayoutVersion" }
splashscreen = { module = "androidx.core:core-splashscreen", version.ref = "splashScreenVersion" }
junit-core = { module = "junit:junit", version.ref = "junitVersion" }
junit-test = { module = "androidx.test.ext:junit", version.ref = "testJunitVersion" }
espresso-test = { module = "androidx.test.espresso:espresso-core", version.ref = "testEspressoVersion" }

lifecycle-runtime = { module = "androidx.lifecycle:lifecycle-runtime-ktx", version.ref = "lifecycleVersion" }
lifecycle-runtime-viewModel = { module = "androidx.lifecycle:lifecycle-viewmodel-ktx", version.ref = "lifecycleVersion" }
lifecycle-runtime-livedata = { module = "androidx.lifecycle:lifecycle-livedata-ktx", version.ref = "lifecycleVersion" }
viewBinding = { module = "androidx.databinding:viewbinding", version.ref = "viewbindingVersion" }
recyclerview = { module = "androidx.recyclerview:recyclerview", version.ref = "recyclerviewVersion" }
recyclerview-animators = { module = "jp.wasabeef:recyclerview-animators", version.ref = "recyclerviewAnimatorsVersion" }

coroutines = { module = "org.jetbrains.kotlinx:kotlinx-coroutines-android", version.ref = "coroutinesVersion" }

moshi = { module = "com.squareup.retrofit2:converter-moshi", version.ref = "retrofitVersion" }
retrofit = { module = "com.squareup.retrofit2:retrofit", version.ref = "retrofitVersion" }
okhttp = { module = "com.squareup.okhttp3:okhttp", version.ref = "okhttpVersion" }
okhttp-logging-interceptor = { module = "com.squareup.okhttp3:logging-interceptor", version.ref = "okhttpVersion" }

room = { module = "androidx.room:room-runtime", version.ref = "roomVersion" }
room-compiler = { module = "androidx.room:room-compiler", version.ref = "roomVersion" }
room-ktx = { module = "androidx.room:room-ktx", version.ref = "roomVersion" }

glide = { module = "com.github.bumptech.glide:glide", version.ref = "glideVersion" }
glide-compiler = { module = "com.github.bumptech.glide:compiler", version.ref = "glideVersion" }

dagger = { module = "com.google.dagger:dagger", version.ref = "daggerVersion" }
dagger-compiler = { module = "com.google.dagger:dagger-compiler", version.ref = "daggerVersion" }

navigation-fragment-ktx = { module = "androidx.navigation:navigation-fragment-ktx", version.ref = "navVersion" }
navigation-ui-ktx = { module = "androidx.navigation:navigation-ui-ktx", version.ref = "navVersion" }
swiperefreshlayout = { module = "androidx.swiperefreshlayout:swiperefreshlayout", version.ref = "swipreRefreshVersion" }


[plugins]
android-application = { id = "com.android.application", version.ref = "androidVersion" }
android-library = { id = "com.android.library", version.ref = "androidVersion" }
kotlin-android = { id = "org.jetbrains.kotlin.android", version.ref = "kotlinVersion" }
kotlin-jvm = { id = "org.jetbrains.kotlin.jvm", version.ref = "kotlinVersion" }

